version: "3"
services:
  app:
    links:
      - db
    build: .
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "9001:9001"
  db:
    image: centos/mysql-57-centos7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    


